openapi: 3.1.0
info:
  title: make87_ntfy
  version: 0.0.0
components:
  schemas:
    "make87_ntfy.publish.MessagePayload":
      properties:
        header:
          properties:
            timestamp:
              type: string
              format: date-time
            referenceId:
              type: string
            entityPath:
              type: string
              description: Slash-based entity path, e.g., "cameras/1/intrinsic"
          additionalProperties: true
          type: object
          title: Header
        topic:
          type: string
          description: 'Required: Target topic name'
        message:
          type: string
          description: Message body; set to triggered if empty or not passed
        title:
          type: string
          description: Message title
        tags:
          items:
            type: string
          type: array
          description: List of tags that may or may not map to emojis
        priority:
          enum:
            - UNKNOWN
            - 0
            - PRIORITY_MIN
            - 1
            - PRIORITY_LOW
            - 2
            - PRIORITY_DEFAULT
            - 3
            - PRIORITY_HIGH
            - 4
            - PRIORITY_MAX
            - 5
          oneOf:
            - type: string
            - type: integer
          title: Priority
        actions:
          items:
            properties:
              label:
                type: string
                description: Label for the action button
              clear:
                type: boolean
                description: Clear notification after HTTP request succeeds. If the request fails, the notification is not cleared.
              view:
                properties:
                  url:
                    type: string
                    description: URL to open
                additionalProperties: true
                type: object
                title: View Action
              broadcast:
                properties:
                  extras:
                    additionalProperties:
                      type: string
                    type: object
                    description: Key-value pairs for broadcast extras
                additionalProperties: true
                type: object
                title: Broadcast Action
              http:
                properties:
                  url:
                    type: string
                    description: URL to send request to
                  method:
                    type: string
                    description: HTTP method (e.g., GET, POST, PUT, DELETE)
                  headers:
                    additionalProperties:
                      type: string
                    type: object
                    description: HTTP headers
                  body:
                    type: string
                    description: HTTP body
                additionalProperties: true
                type: object
                title: Http Action
            additionalProperties: true
            type: object
            allOf:
              - oneOf:
                  - not:
                      anyOf:
                        - required:
                            - view
                        - required:
                            - broadcast
                        - required:
                            - http
                  - required:
                      - view
                  - required:
                      - broadcast
                  - required:
                      - http
            title: Action
          type: array
          description: Custom user action buttons for notifications
        click:
          type: string
          description: Website opened when notification is clicked
        attach:
          type: string
          description: URL of an attachment
        markdown:
          type: boolean
          description: Set to true if the message is Markdown-formatted
        icon:
          type: string
          description: URL to use as notification icon
        filename:
          type: string
          description: File name of the attachment
        delay:
          type: string
          description: Timestamp or duration for delayed delivery
        email:
          type: string
          description: E-mail address for e-mail notifications
        call:
          type: string
          description: Phone number to use for voice call (or "yes")
      additionalProperties: true
      type: object
      title: Message Payload
