name: Generate OpenAPI Schema Manifest

on:
  push:
    branches: [ "**" ]
  pull_request:

permissions:
  contents: write

env:
  DEPENDENCY_REPO: make87-messages/make87_messages

jobs:
  generate-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Get current repo name
        id: current
        run: |
          echo "name=${GITHUB_REPOSITORY##*/}" >> $GITHUB_OUTPUT

      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          path: ${{ steps.current.outputs.name }}

      - name: Checkout messages repo if different
        if: ${{ github.repository != env.DEPENDENCY_REPO }}
        uses: actions/checkout@v4
        with:
          repository: ${{ env.DEPENDENCY_REPO }}
          path: make87_messages

      - name: Determine PROTO_DIR
        run: |
          if [ "${GITHUB_REPOSITORY}" != "${DEPENDENCY_REPO}" ]; then
            echo "PROTO_DIR=${{ steps.current.outputs.name }}" >> $GITHUB_ENV
          else
            echo "PROTO_DIR=make87_messages" >> $GITHUB_ENV
          fi

      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Generate descriptor.pb from proto
        run: |
          find $PROTO_DIR -name '*.proto' > proto_files.txt
          protoc \
            --include_imports \
            --descriptor_set_out=descriptor.pb \
            -I . \
            --proto_path=. \
            $(cat proto_files.txt)

      - name: Download proto_parser binary
        run: |
          wget https://make87-files.nyc3.digitaloceanspaces.com/releases/latest/proto_parser-x86_64-unknown-linux-gnu -O proto_parser
          chmod +x proto_parser

      - name: Generate MAKE87.schemas.yml from descriptor.pb
        run: |
          ./proto_parser --output MAKE87.schemas.yml descriptor.pb

      - name: Commit schema file to branch (optional)
        if: github.ref_type == 'branch' && github.event_name != 'pull_request'
        run: |
          cp MAKE87.schemas.yml $PROTO_DIR/MAKE87.schemas.yml
          cd $PROTO_DIR
          git config user.name "make87 bot"
          git config user.email "bot@make87.com"
          git add MAKE87.schemas.yml
          git commit -m "chore: regenerate MAKE87.schemas.yml" || echo "No changes to commit"
          git push origin HEAD
